name: var_app
description: "Var_IPTV"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Streaming
  http: ^1.2.0
  video_player: ^2.9.1
  wakelock_plus: ^1.2.8
  device_info_plus: ^10.1.2

  # UI / Utils
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/

    - assets/bein/
    - assets/dazn/
    - assets/espn/
    - assets/mbc/
    - assets/roshnleague/
    - assets/premierleague/
    - assets/generalsports/
    - assets/SeriaA/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_monochrome: "assets/images/logo.png"

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#000000"
